CREATE TABLE `branches` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`resort` INT(11) NULL DEFAULT NULL,
	`school` INT(11) NULL DEFAULT NULL,
	`address` VARCHAR(150) NULL DEFAULT NULL,
	`address_code` INT(11) NULL DEFAULT NULL,
	`branch_code` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(150) NULL DEFAULT NULL,
	`map_x` DOUBLE NOT NULL DEFAULT '0',
	`map_y` DOUBLE NOT NULL DEFAULT '0',
	`region` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
	COLLATE='utf8mb4_general_ci'
	ENGINE=InnoDB;